version: '3.9'

services:
  backend-service:
    image: ruby:3.3.6-bullseye
    volumes:
      - .:/app
    working_dir: /app
    environment:
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_HOST: postgres
      REDIS_HOST: redis
    command: sh -c "rm -f tmp/pids/server.pid && bundle install && rails server -b 0.0.0.0 -e development && tail -f log/development.log"
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    networks:
      - social-network

  db:
    container_name: postgres
    image: postgres:17.2-alpine3.21
    ports:
      - "5432:5432"
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: social_network
    networks:
      - social-network

  redis:
    container_name: redis
    image: redis:7.4.1-alpine
    ports:
      - "6379:6379"
    restart: always
    networks:
      - social-network
networks:
  social-network:
    driver: bridge