version: '3.9'

services:
  db:
    image: postgres:17.2-alpine3.21
    ports:
      - "5432:5432"
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: social_network

  redis:
    image: redis:7.4.1-alpine
    ports:
      - "6379:6379"
    restart: always
    networks:
      - social-network
networks:
  social-network:
    driver: bridge