---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/auth/registration":
    post:
      summary: Registration new account
      tags:
      - Auth
      parameters: []
      responses:
        '201':
          description: Account successfully created
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: phihai91@1.com
                password:
                  type: string
                  example: "@StrongPassword123!"
              required:
              - email
              - password
  "/api/v1/auth/login":
    post:
      summary: Login to account
      tags:
      - Auth
      parameters: []
      responses:
        '401':
          description: Unauthorized - Invalid credentials
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: user@example.com
                password:
                  type: string
                  example: StrongPassword123!
              required:
              - email
              - password
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
